ScoreToWin = 40
TimePerFrameInMs = 300

[board]

EmptyTileSymbol = " "
Height = 30
Width = 30

[snake]

BodyColor = "green"
BodySymbol = "#"

HeadColor = "yellow"
HeadSymbol = "$"

X = 10
Y = 10

MovementDirection = "right"

[food]

Color = "red"
Symbol = "@"

X = 15
Y = 15

[keyboard]

Up = "w"
Left = "a"
Down = "s"
Right = "d"

Quit = "q"
